- build: examples/2-tft-basic
  photon: [0.6.3, 0.7.0, 1.0.0]
  p1: [1.0.0]
  electron: [1.0.0]
  argon: [0.8.0-rc.27]
  boron: [0.8.0-rc.27]
  xenon: [0.8.0-rc.27]
- build: examples/3-tft-graphicstest
  argon: [0.8.0-rc.27]
